### ISSUE TITLE
Build getting failed due to the peerDependencies of @ember/test-helpers: `^2.0.0`;

### ISSUE THREAD

**Issue by vishnubalajikm** [ember-a11y/ember-a11y-testing#269]
Am using the latest version, which is enforcing the peer dependency of @ember/test-helpers >= 2.0.0. After installing the @ember/test-helpers(v2.2.6), my build is getting an error.

Ember - v3.16.2
Node - v12.18.0

```
building... [Babel: @ember/test-helpers > applyPatches]internal/worker.js:279
    this[kPublicPort].postMessage(...args);

DOMException [DataCloneError]: function(opts, cb) {
  var options = getOptions(opts, cb);

  // options.error and options.success are for libs...<omitted>...
} could not be cloned.
    at Worker.postMessage (internal/worker.js:279:23)
    at Worker.worker.send (/Users/vb/Dev/frontend/node_modules/broccoli-babel-transpiler/node_modules/workerpool/src/WorkerHandler.js:108:10)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (/Users/vb/Dev/frontend/node_modules/broccoli-babel-transpiler/node_modules/workerpool/src/WorkerHandler.js:253:21)
    at Worker.<anonymous> (/Users/vb/Dev/frontend/node_modules/broccoli-babel-transpiler/node_modules/workerpool/src/WorkerHandler.js:208:7)
    at Worker.emit (events.js:315:20)
    at Worker.EventEmitter.emit (domain.js:482:12)
    at MessagePort.<anonymous> (internal/worker.js:192:55)
    at MessagePort.emit (events.js:315:20)
    at MessagePort.EventEmitter.emit (domain.js:482:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by NullVoxPopuli** [comment]
I'm running in to this as well.
```
❯ yarn lint:dependency
yarn run v1.22.11
warning ../../package.json: No license field
$ ember dependency-lint
@ember/test-waiters
Allowed: 2.4.5 || 2.4.3
Found: 3.0.0, 2.4.3
ember-cheat-sheet
├─┬ @ember/test-helpers
│ └── @ember/test-waiters@3.0.0
└─┬ ember-a11y-testing
  └── @ember/test-waiters@2.4.3
```

For now, I'll have to remove a11y-testing and come back to it

**Comment by NullVoxPopuli** [comment]
seems removing it doesn't even fix the dep lint. Guess I'll disable the dep lint instead....

**Comment by SergeAstapov** [comment]
@NullVoxPopuli @vishnubalajikm can you give this another try? currently this package has `"@ember/test-waiters": "^2.4.3 || ^3.0.0"` in `package.json`

**Comment by NullVoxPopuli** [comment]
I've been removing dependency lint whenever I can :see_no_evil:

**Comment by MelSumner** [comment]
I'm going to close this issue since I think it was resolved a long time ago. Please re-open if you are still encountering the issue, thanks!
