### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by goyalvarun601** [ember-a11y/ember-a11y-testing#76]
I get the module not found error when I try to import the module in my integration tests.
It works fine in the dev environment, I can see the violations in the browser.
Here are the versions that I am using:
ember: 1.13.5
ember-cli: 1.13.15
node: 4.4.7
npm: 2.14.10

Any suggestions on what may be wrong here?

**Comment by trentmwillis** [comment]
Can you post the exact error and stack trace you are encountering? Otherwise we have no idea which module is not being found and the potential reason for it not loading.

Also, a reproduction either via ember-twiddle or a github repo would be helpful if you have the time to put them together.

**Comment by goyalvarun601** [comment]
Died on test #1     at TestLoader.moduleLoadFailure (http://localhost:7357/assets/test-support.js:6001:11)
    at TestLoader.require (http://localhost:7357/assets/test-loader.js:62:14)
    at http://localhost:7357/assets/test-support.js:7852:22
    at Array.forEach (native)
    at TestLoader._loadSplitModules [as loadModules] (http://localhost:7357/assets/test-support.js:7851:18)
    at Function.TestLoader.load (http://localhost:7357/assets/test-loader.js:82:24)
    at http://localhost:7357/assets/test-support.js:6010:16: Could not find module `ember-a11y-testing/test-support/audit` imported from `connect-paam/tests/integration/activity-intro-page-test`@ 1 ms
Source: 	
Error: Could not find module `ember-a11y-testing/test-support/audit` imported from `connect-paam/tests/integration/activity-intro-page-test`
    at missingModule (http://localhost:7357/assets/vendor.js:144:11)
    at findModule (http://localhost:7357/assets/vendor.js:159:17)
    at Module.reify (http://localhost:7357/assets/vendor.js:95:22)
    at Module.build (http://localhost:7357/assets/vendor.js:113:23)
    at findModule (http://localhost:7357/assets/vendor.js:161:9)
    at requireModule (http://localhost:7357/assets/vendor.js:148:12)
    at TestLoader.require (http://localhost:7357/assets/test-loader.js:60:9)
    at http://localhost:7357/assets/test-support.js:7852:22
    at Array.forEach (native)
    at TestLoader._loadSplitModules [as loadModules] (http://localhost:7357/assets/test-support.js:7851:18)

Does this help?

**Comment by trentmwillis** [comment]
Sorry for the delaying in responding. If you're still experiencing the issue, what version of `ember-a11y-testing` is your application using? Is there a reproduction of the issue that you could share?
